import React, { createContext, useContext, useState, useEffect } from 'react'

type Language = 'en' | 'krio' | 'fr'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

export type { Language }

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.invoices': 'Invoices',
    'nav.customers': 'Customers',
    'nav.inventory': 'Inventory',
    'nav.sales': 'Sales',
    'nav.expenses': 'Expenses',
    'nav.suppliers': 'Suppliers',
    'nav.reports': 'Reports',
    'nav.credit': 'Credit & Finance',
    'nav.settings': 'Settings',
    'nav.mainmenu': 'Main Menu',
    
    // Common UI
    'common.search': 'Search transactions, customers...',
    'common.profile': 'Profile',
    'common.signout': 'Sign out',
    'common.notifications': 'Notifications',
    'common.administrator': 'Administrator',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.view': 'View',
    'common.add': 'Add',
    'common.create': 'Create',
    'common.update': 'Update',
    'common.close': 'Close',
    'common.confirm': 'Confirm',
    'common.loading': 'Loading...',
    'common.actions': 'Actions',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.print': 'Print',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.previous': 'Previous',
    'common.finish': 'Finish',
    'common.all': 'All',
    'common.none': 'None',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.tax': 'Tax',
    'common.discount': 'Discount',
    'common.name': 'Name',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.description': 'Description',
    'common.notes': 'Notes',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.unit': 'Unit',
    'common.category': 'Category',
    'common.type': 'Type',
    'common.details': 'Details',
    'common.summary': 'Summary',
    'common.from': 'From',
    'common.to': 'To',
    'common.today': 'Today',
    'common.yesterday': 'Yesterday',
    'common.thisWeek': 'This Week',
    'common.lastWeek': 'Last Week',
    'common.thisMonth': 'This Month',
    'common.lastMonth': 'Last Month',
    'common.thisYear': 'This Year',
    'common.select': 'Select',
    
    // Dashboard
    'dashboard.welcome': 'Welcome to MiBuks',
    'dashboard.goodMorning': 'Good Morning',
    'dashboard.goodAfternoon': 'Good Afternoon',
    'dashboard.goodEvening': 'Good Evening',
    'dashboard.yourBusiness': 'Your Business',
    'dashboard.user': 'User',
    'dashboard.welcomeTo': 'Welcome to',
    'dashboard.metrics': 'Key Metrics',
    'dashboard.totalRevenue': 'Total Revenue',
    'dashboard.fromSales': 'from sales & invoices',
    'dashboard.activeCustomers': 'Active Customers',
    'dashboard.totalCustomers': 'total customers',
    'dashboard.inventoryValue': 'Inventory Value',
    'dashboard.currentStock': 'current stock',
    'dashboard.todaySales': "Today's Sales",
    'dashboard.lowStock': 'Low Stock Items',
    'dashboard.pendingInvoices': 'Pending Invoices',
    'dashboard.invoices': 'invoices',
    'dashboard.awaitingPayment': 'awaiting payment',
    'dashboard.revenueOverview': 'Revenue Overview',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.commonOperations': 'Common operations',
    'dashboard.recordSale': 'Record Sale',
    'dashboard.createInvoice': 'Create Invoice',
    'dashboard.addCustomer': 'Add Customer',
    'dashboard.restockItem': 'Restock Item',
    'dashboard.recentTransactions': 'Recent Transactions',
    'dashboard.viewAll': 'View All',
    
    // Sales
    'sales.title': 'Sales Management',
    'sales.recordSale': 'Record Sale',
    'sales.saleHistory': 'Sale History',
    'sales.customer': 'Customer',
    'sales.items': 'Items',
    'sales.totalAmount': 'Total Amount',
    'sales.paymentMethod': 'Payment Method',
    'sales.cash': 'Cash',
    'sales.card': 'Card',
    'sales.mobileMoney': 'Mobile Money',
    'sales.credit': 'Credit',
    'sales.selectCustomer': 'Select Customer',
    'sales.addItem': 'Add Item',
    'sales.item': 'Item',
    'sales.unitPrice': 'Unit Price',
    'sales.receiptGenerated': 'Receipt Generated',
    'sales.viewReceipt': 'View Receipt',
    'sales.printReceipt': 'Print Receipt',
    'sales.date': 'Date',
    'sales.time': 'Time',
    'sales.itemsSold': 'Items Sold',
    'sales.noSales': 'No sales recorded yet',
    
    // Inventory
    'inventory.title': 'Inventory Management',
    'inventory.description': 'Manage your stock levels and inventory',
    'inventory.loading': 'Loading inventory...',
    'inventory.addItem': 'Add Item',
    'inventory.restock': 'Restock',
    'inventory.productName': 'Product Name',
    'inventory.sku': 'SKU',
    'inventory.stock': 'Stock',
    'inventory.lowStock': 'Low Stock',
    'inventory.inStock': 'In Stock',
    'inventory.outOfStock': 'Out of Stock',
    'inventory.reorderLevel': 'Reorder Level',
    'inventory.costPrice': 'Cost Price',
    'inventory.sellingPrice': 'Selling Price',
    'inventory.supplier': 'Supplier',
    'inventory.barcode': 'Barcode',
    'inventory.stockValue': 'Stock Value',
    'inventory.addQuantity': 'Add Quantity',
    'inventory.currentStock': 'Current Stock',
    'inventory.newStock': 'New Stock',
    'inventory.noItems': 'No inventory items yet',
    'inventory.totalItems': 'Total Items',
    'inventory.totalValue': 'Total Value',
    'inventory.allItems': 'All Items',
    'inventory.critical': 'Critical',
    'inventory.stockOverview': 'Stock Overview',
    'inventory.items': 'items',
    'inventory.no': 'No',
    'inventory.stockItems': 'stock items',
    'inventory.addFirst': 'Add Your First Item',
    'inventory.deleteItem': 'Delete Item',
    'inventory.deleteConfirm': 'Are you sure you want to delete',
    
    // Invoices
    'invoices.title': 'Invoices',
    'invoices.description': 'Create and manage invoices',
    'invoices.loading': 'Loading invoices...',
    'invoices.create': 'Create Invoice',
    'invoices.createInvoice': 'Create Invoice',
    'invoices.confirmDelete': 'Are you sure you want to delete this invoice?',
    'invoices.invoiceNumber': 'Invoice Number',
    'invoices.invoiceDate': 'Invoice Date',
    'invoices.dueDate': 'Due Date',
    'invoices.billTo': 'Bill To',
    'invoices.billFrom': 'Bill From',
    'invoices.paid': 'Paid',
    'invoices.unpaid': 'Unpaid',
    'invoices.overdue': 'Overdue',
    'invoices.partial': 'Partially Paid',
    'invoices.cancelled': 'Cancelled',
    'invoices.draft': 'Draft',
    'invoices.issued': 'Issued',
    'invoices.amountDue': 'Amount Due',
    'invoices.amountPaid': 'Amount Paid',
    'invoices.balance': 'Balance',
    'invoices.sendInvoice': 'Send Invoice',
    'invoices.markAsPaid': 'Mark as Paid',
    'invoices.applyCredit': 'Apply Credit',
    'invoices.noInvoices': 'No invoices yet',
    
    // Customers
    'customers.title': 'Customers',
    'customers.addCustomer': 'Add Customer',
    'customers.firstName': 'First Name',
    'customers.lastName': 'Last Name',
    'customers.companyName': 'Company Name',
    'customers.contactPerson': 'Contact Person',
    'customers.totalSpent': 'Total Spent',
    'customers.lastPurchase': 'Last Purchase',
    'customers.creditBalance': 'Credit Balance',
    'customers.birthdate': 'Birth Date',
    'customers.notes': 'Customer Notes',
    'customers.purchaseHistory': 'Purchase History',
    'customers.noCustomers': 'No customers yet',
    
    // Suppliers
    'suppliers.title': 'Suppliers',
    'suppliers.addSupplier': 'Add Supplier',
    'suppliers.supplierName': 'Supplier Name',
    'suppliers.totalOrders': 'Total Orders',
    'suppliers.lastOrder': 'Last Order',
    'suppliers.outstanding': 'Outstanding',
    'suppliers.products': 'Products Supplied',
    'suppliers.noSuppliers': 'No suppliers yet',
    
    // Expenses
    'expenses.title': 'Expenses',
    'expenses.addExpense': 'Add Expense',
    'expenses.expenseCategory': 'Expense Category',
    'expenses.rent': 'Rent',
    'expenses.utilities': 'Utilities',
    'expenses.salaries': 'Salaries',
    'expenses.supplies': 'Supplies',
    'expenses.marketing': 'Marketing',
    'expenses.transport': 'Transport',
    'expenses.maintenance': 'Maintenance',
    'expenses.other': 'Other',
    'expenses.receipt': 'Receipt',
    'expenses.uploadReceipt': 'Upload Receipt',
    'expenses.totalExpenses': 'Total Expenses',
    'expenses.noExpenses': 'No expenses recorded yet',
    
    // Reports
    'reports.title': 'Reports & Analytics',
    'reports.salesReport': 'Sales Report',
    'reports.inventoryReport': 'Inventory Report',
    'reports.profitLoss': 'Profit & Loss',
    'reports.cashFlow': 'Cash Flow',
    'reports.taxReport': 'Tax Report',
    'reports.generateReport': 'Generate Report',
    'reports.period': 'Period',
    'reports.exportPDF': 'Export PDF',
    'reports.exportExcel': 'Export Excel',
    'reports.revenue': 'Revenue',
    'reports.expenses': 'Expenses',
    'reports.profit': 'Profit',
    'reports.loss': 'Loss',
    'reports.netIncome': 'Net Income',
    
    // Credit & Finance
    'credit.title': 'Credit & Finance',
    'credit.creditScore': 'Credit Score',
    'credit.loanApplications': 'Loan Applications',
    'credit.applyForLoan': 'Apply for Loan',
    'credit.loanAmount': 'Loan Amount',
    'credit.loanPurpose': 'Loan Purpose',
    'credit.repaymentPeriod': 'Repayment Period',
    'credit.monthlyPayment': 'Monthly Payment',
    'credit.interestRate': 'Interest Rate',
    'credit.approved': 'Approved',
    'credit.pending': 'Pending',
    'credit.rejected': 'Rejected',
    'credit.creditHistory': 'Credit History',
    
    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.business': 'Business',
    'settings.team': 'Team',
    'settings.security': 'Security',
    'settings.notifications': 'Notifications',
    'settings.preferences': 'Preferences',
    'settings.data': 'Data',
    'settings.profileInfo': 'Profile Information',
    'settings.businessInfo': 'Business Information',
    'settings.firstName': 'First Name',
    'settings.lastName': 'Last Name',
    'settings.phoneNumber': 'Phone Number',
    'settings.emailAddress': 'Email Address',
    'settings.businessName': 'Business Name',
    'settings.businessType': 'Business Type',
    'settings.businessAddress': 'Business Address',
    'settings.taxRate': 'Tax Rate',
    'settings.currency': 'Currency',
    'settings.changePassword': 'Change Password',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm Password',
    'settings.twoFactor': 'Two-Factor Authentication',
    'settings.emailNotifications': 'Email Notifications',
    'settings.smsNotifications': 'SMS Notifications',
    'settings.lowStockAlerts': 'Low Stock Alerts',
    'settings.newOrderAlerts': 'New Order Alerts',
    'settings.paymentAlerts': 'Payment Alerts',
    'settings.theme': 'Theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.system': 'System',
    'settings.language': 'Language',
    'settings.dateFormat': 'Date Format',
    'settings.timeFormat': 'Time Format',
    'settings.autoBackup': 'Automatic Backup',
    'settings.compactView': 'Compact View',
    'settings.exportData': 'Export Data',
    'settings.importData': 'Import Data',
    'settings.deleteAccount': 'Delete Account',
    'settings.saveChanges': 'Save Changes',
    'settings.teamManagement': 'Team Management',
    'settings.inviteMember': 'Invite Member',
    'settings.memberRole': 'Member Role',
    'settings.owner': 'Owner',
    'settings.manager': 'Manager',
    'settings.staff': 'Staff',
    'settings.accountSecurity': 'Account Security',
    'settings.loginHistory': 'Login History',
    'settings.weeklyReports': 'Weekly Reports',
    'settings.monthlyReports': 'Monthly Reports',
    
    // Auth
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.welcomeBack': 'Welcome Back',
    'auth.createAccount': 'Create Account',
    'auth.enterEmail': 'Enter your email',
    'auth.enterPassword': 'Enter your password',
    'auth.forgotPassword': 'Forgot Password?',
    'auth.noAccount': "Don't have an account?",
    'auth.haveAccount': 'Already have an account?',
    'auth.signInGoogle': 'Sign in with Google',
    'auth.or': 'OR',
    
    // Onboarding
    'onboarding.welcome': 'Welcome to MiBuks',
    'onboarding.getStarted': "Let's get started",
    'onboarding.step1': 'Personal Details',
    'onboarding.step2': 'Business Details',
    'onboarding.step3': 'Complete',
    'onboarding.tellUs': 'Tell us about yourself',
    'onboarding.businessDetails': 'Tell us about your business',
    'onboarding.almostDone': 'Almost done!',
    'onboarding.complete': 'Complete Setup',
    'onboarding.skip': 'Skip for now',
    
    // Language
    'language.english': 'English',
    'language.krio': 'Krio',
    'language.french': 'French',
    'language.switch': 'Switch Language',
    
    // Business
    'business.defaultname': 'My Business',
    
    // Messages
    'message.success': 'Success',
    'message.error': 'Error',
    'message.saved': 'Saved successfully',
    'message.deleted': 'Deleted successfully',
    'message.updated': 'Updated successfully',
    'message.created': 'Created successfully',
    'message.failed': 'Operation failed',
    'message.confirm.delete': 'Are you sure you want to delete this?',
    'message.confirm.cancel': 'Are you sure you want to cancel?',
    'message.noData': 'No data available',
    'message.noResults': 'No results found',
  },
  krio: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.invoices': 'Invoice dem',
    'nav.customers': 'Customer dem',
    'nav.inventory': 'Inventory',
    'nav.sales': 'Sales dem',
    'nav.expenses': 'Expense dem',
    'nav.suppliers': 'Supplier dem',
    'nav.reports': 'Report dem',
    'nav.credit': 'Credit & Finance',
    'nav.settings': 'Settings',
    'nav.mainmenu': 'Main Menu',
    
    // Common UI
    'common.search': 'Find transaction, customer dem...',
    'common.profile': 'Profile',
    'common.signout': 'Comot',
    'common.notifications': 'Notification dem',
    'common.administrator': 'Administrator',
    'common.save': 'Sev am',
    'common.cancel': 'Cancel',
    'common.delete': 'Delet',
    'common.edit': 'Edit',
    'common.view': 'Luk',
    'common.add': 'Add',
    'common.create': 'Mek',
    'common.update': 'Update',
    'common.close': 'Klos',
    'common.confirm': 'Confirm',
    'common.loading': 'E de load...',
    'common.actions': 'Wetin fo du',
    'common.filter': 'Filter',
    'common.export': 'Export',
    'common.import': 'Import',
    'common.print': 'Print',
    'common.download': 'Download',
    'common.upload': 'Upload',
    'common.submit': 'Submit',
    'common.reset': 'Reset',
    'common.back': 'Go bak',
    'common.next': 'Neks',
    'common.previous': 'Bifo',
    'common.finish': 'Finish',
    'common.all': 'Ol',
    'common.none': 'Non',
    'common.yes': 'Yes',
    'common.no': 'No',
    'common.status': 'Status',
    'common.date': 'Date',
    'common.amount': 'Amount',
    'common.total': 'Total',
    'common.subtotal': 'Subtotal',
    'common.tax': 'Tax',
    'common.discount': 'Discount',
    'common.name': 'Nem',
    'common.email': 'Email',
    'common.phone': 'Phone',
    'common.address': 'Address',
    'common.description': 'Description',
    'common.notes': 'Notes',
    'common.price': 'Price',
    'common.quantity': 'Quantity',
    'common.unit': 'Unit',
    'common.category': 'Category',
    'common.type': 'Type',
    'common.details': 'Details',
    'common.summary': 'Summary',
    'common.from': 'From',
    'common.to': 'To',
    'common.today': 'Tide',
    'common.yesterday': 'Yestaday',
    'common.thisWeek': 'Dis Week',
    'common.lastWeek': 'Las Week',
    'common.thisMonth': 'Dis Month',
    'common.lastMonth': 'Las Month',
    'common.thisYear': 'Dis Year',
    'common.select': 'Pik',
    
    // Dashboard
    'dashboard.welcome': 'Welkam to MiBuks',
    'dashboard.goodMorning': 'Good Mornin',
    'dashboard.goodAfternoon': 'Good Afternoon',
    'dashboard.goodEvening': 'Good Evenin',
    'dashboard.yourBusiness': 'Yu Biznes',
    'dashboard.user': 'User',
    'dashboard.welcomeTo': 'Welkam to',
    'dashboard.metrics': 'Key Metrics',
    'dashboard.totalRevenue': 'Total Revenue',
    'dashboard.fromSales': 'from sales & invoices',
    'dashboard.activeCustomers': 'Active Customers',
    'dashboard.totalCustomers': 'total customers',
    'dashboard.inventoryValue': 'Inventory Value',
    'dashboard.currentStock': 'current stock',
    'dashboard.todaySales': 'Tide Sales',
    'dashboard.lowStock': 'Low Stock Items',
    'dashboard.pendingInvoices': 'Pending Invoices',
    'dashboard.invoices': 'invoices',
    'dashboard.awaitingPayment': 'awaiting payment',
    'dashboard.revenueOverview': 'Revenue Overview',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.commonOperations': 'Common operations',
    'dashboard.recordSale': 'Rekod Sale',
    'dashboard.createInvoice': 'Mek Invoice',
    'dashboard.addCustomer': 'Add Customer',
    'dashboard.restockItem': 'Restock Item',
    'dashboard.recentTransactions': 'Recent Transactions',
    'dashboard.viewAll': 'Luk Ol',
    
    // Sales
    'sales.title': 'Sales Management',
    'sales.recordSale': 'Rekod Sale',
    'sales.saleHistory': 'Sale History',
    'sales.customer': 'Customer',
    'sales.items': 'Items',
    'sales.totalAmount': 'Total Amount',
    'sales.paymentMethod': 'Payment Method',
    'sales.cash': 'Cash',
    'sales.card': 'Card',
    'sales.mobileMoney': 'Mobile Money',
    'sales.credit': 'Credit',
    'sales.selectCustomer': 'Pik Customer',
    'sales.addItem': 'Add Item',
    'sales.item': 'Item',
    'sales.unitPrice': 'Unit Price',
    'sales.receiptGenerated': 'Receipt Don Generate',
    'sales.viewReceipt': 'Luk Receipt',
    'sales.printReceipt': 'Print Receipt',
    'sales.date': 'Date',
    'sales.time': 'Time',
    'sales.itemsSold': 'Items Wey Dem Sell',
    'sales.noSales': 'No sales yet',
    
    // Inventory
    'inventory.title': 'Inventory Management',
    'inventory.description': 'Manage yu stock levels and inventory',
    'inventory.loading': 'E de load inventory...',
    'inventory.addItem': 'Add Item',
    'inventory.restock': 'Restock',
    'inventory.productName': 'Product Nem',
    'inventory.sku': 'SKU',
    'inventory.stock': 'Stock',
    'inventory.lowStock': 'Low Stock',
    'inventory.inStock': 'Na dey',
    'inventory.outOfStock': 'No dey',
    'inventory.reorderLevel': 'Reorder Level',
    'inventory.costPrice': 'Cost Price',
    'inventory.sellingPrice': 'Selling Price',
    'inventory.supplier': 'Supplier',
    'inventory.barcode': 'Barcode',
    'inventory.stockValue': 'Stock Value',
    'inventory.addQuantity': 'Add Quantity',
    'inventory.currentStock': 'Current Stock',
    'inventory.newStock': 'New Stock',
    'inventory.noItems': 'No inventory items',
    'inventory.totalItems': 'Total Items',
    'inventory.totalValue': 'Total Value',
    'inventory.allItems': 'Ol Items',
    'inventory.critical': 'Critical',
    'inventory.stockOverview': 'Stock Overview',
    'inventory.items': 'items',
    'inventory.no': 'No',
    'inventory.stockItems': 'stock items',
    'inventory.addFirst': 'Add Yu First Item',
    'inventory.deleteItem': 'Delete Item',
    'inventory.deleteConfirm': 'Yu sure sey yu wan delete',
    
    // Invoices
    'invoices.title': 'Invoices',
    'invoices.description': 'Mek en manage invoices',
    'invoices.loading': 'E de load invoices...',
    'invoices.create': 'Mek Invoice',
    'invoices.createInvoice': 'Mek Invoice',
    'invoices.confirmDelete': 'Yu sure sey yu wan delete dis invoice?',
    'invoices.invoiceNumber': 'Invoice Number',
    'invoices.invoiceDate': 'Invoice Date',
    'invoices.dueDate': 'Due Date',
    'invoices.billTo': 'Bill To',
    'invoices.billFrom': 'Bill From',
    'invoices.paid': 'Paid',
    'invoices.unpaid': 'No Pay Yet',
    'invoices.overdue': 'Overdue',
    'invoices.partial': 'Partial Pay',
    'invoices.cancelled': 'Cancelled',
    'invoices.draft': 'Draft',
    'invoices.issued': 'Issued',
    'invoices.amountDue': 'Amount Wey Dem Owe',
    'invoices.amountPaid': 'Amount Wey Dem Pay',
    'invoices.balance': 'Balance',
    'invoices.sendInvoice': 'Send Invoice',
    'invoices.markAsPaid': 'Mark as Paid',
    'invoices.applyCredit': 'Apply Credit',
    'invoices.noInvoices': 'No invoices',
    
    // Customers
    'customers.title': 'Customers',
    'customers.addCustomer': 'Add Customer',
    'customers.firstName': 'First Nem',
    'customers.lastName': 'Last Nem',
    'customers.companyName': 'Company Nem',
    'customers.contactPerson': 'Contact Person',
    'customers.totalSpent': 'Total Wey E Spend',
    'customers.lastPurchase': 'Las Purchase',
    'customers.creditBalance': 'Credit Balance',
    'customers.birthdate': 'Birthday',
    'customers.notes': 'Customer Notes',
    'customers.purchaseHistory': 'Purchase History',
    'customers.noCustomers': 'No customers',
    
    // Suppliers
    'suppliers.title': 'Suppliers',
    'suppliers.addSupplier': 'Add Supplier',
    'suppliers.supplierName': 'Supplier Nem',
    'suppliers.totalOrders': 'Total Orders',
    'suppliers.lastOrder': 'Las Order',
    'suppliers.outstanding': 'Outstanding',
    'suppliers.products': 'Products Wey E Supply',
    'suppliers.noSuppliers': 'No suppliers',
    
    // Expenses
    'expenses.title': 'Expenses',
    'expenses.addExpense': 'Add Expense',
    'expenses.expenseCategory': 'Expense Category',
    'expenses.rent': 'Rent',
    'expenses.utilities': 'Utilities',
    'expenses.salaries': 'Salaries',
    'expenses.supplies': 'Supplies',
    'expenses.marketing': 'Marketing',
    'expenses.transport': 'Transport',
    'expenses.maintenance': 'Maintenance',
    'expenses.other': 'Other',
    'expenses.receipt': 'Receipt',
    'expenses.uploadReceipt': 'Upload Receipt',
    'expenses.totalExpenses': 'Total Expenses',
    'expenses.noExpenses': 'No expenses',
    
    // Reports
    'reports.title': 'Reports & Analytics',
    'reports.salesReport': 'Sales Report',
    'reports.inventoryReport': 'Inventory Report',
    'reports.profitLoss': 'Profit & Loss',
    'reports.cashFlow': 'Cash Flow',
    'reports.taxReport': 'Tax Report',
    'reports.generateReport': 'Generate Report',
    'reports.period': 'Period',
    'reports.exportPDF': 'Export PDF',
    'reports.exportExcel': 'Export Excel',
    'reports.revenue': 'Revenue',
    'reports.expenses': 'Expenses',
    'reports.profit': 'Profit',
    'reports.loss': 'Loss',
    'reports.netIncome': 'Net Income',
    
    // Credit & Finance
    'credit.title': 'Credit & Finance',
    'credit.creditScore': 'Credit Score',
    'credit.loanApplications': 'Loan Applications',
    'credit.applyForLoan': 'Apply fo Loan',
    'credit.loanAmount': 'Loan Amount',
    'credit.loanPurpose': 'Loan Purpose',
    'credit.repaymentPeriod': 'Repayment Period',
    'credit.monthlyPayment': 'Monthly Payment',
    'credit.interestRate': 'Interest Rate',
    'credit.approved': 'Approved',
    'credit.pending': 'Pending',
    'credit.rejected': 'Rejected',
    'credit.creditHistory': 'Credit History',
    
    // Settings
    'settings.title': 'Settings',
    'settings.profile': 'Profile',
    'settings.business': 'Business',
    'settings.team': 'Team',
    'settings.security': 'Security',
    'settings.notifications': 'Notifications',
    'settings.preferences': 'Preferences',
    'settings.data': 'Data',
    'settings.profileInfo': 'Profile Information',
    'settings.businessInfo': 'Business Information',
    'settings.firstName': 'First Nem',
    'settings.lastName': 'Last Nem',
    'settings.phoneNumber': 'Phone Number',
    'settings.emailAddress': 'Email Address',
    'settings.businessName': 'Business Nem',
    'settings.businessType': 'Business Type',
    'settings.businessAddress': 'Business Address',
    'settings.taxRate': 'Tax Rate',
    'settings.currency': 'Currency',
    'settings.changePassword': 'Change Password',
    'settings.currentPassword': 'Current Password',
    'settings.newPassword': 'New Password',
    'settings.confirmPassword': 'Confirm Password',
    'settings.twoFactor': 'Two-Factor Authentication',
    'settings.emailNotifications': 'Email Notifications',
    'settings.smsNotifications': 'SMS Notifications',
    'settings.lowStockAlerts': 'Low Stock Alerts',
    'settings.newOrderAlerts': 'New Order Alerts',
    'settings.paymentAlerts': 'Payment Alerts',
    'settings.theme': 'Theme',
    'settings.light': 'Light',
    'settings.dark': 'Dark',
    'settings.system': 'System',
    'settings.language': 'Language',
    'settings.dateFormat': 'Date Format',
    'settings.timeFormat': 'Time Format',
    'settings.autoBackup': 'Automatic Backup',
    'settings.compactView': 'Compact View',
    'settings.exportData': 'Export Data',
    'settings.importData': 'Import Data',
    'settings.deleteAccount': 'Delete Account',
    'settings.saveChanges': 'Sev Changes',
    'settings.teamManagement': 'Team Management',
    'settings.inviteMember': 'Invite Member',
    'settings.memberRole': 'Member Role',
    'settings.owner': 'Owner',
    'settings.manager': 'Manager',
    'settings.staff': 'Staff',
    'settings.accountSecurity': 'Account Security',
    'settings.loginHistory': 'Login History',
    'settings.weeklyReports': 'Weekly Reports',
    'settings.monthlyReports': 'Monthly Reports',
    
    // Auth
    'auth.signIn': 'Sign In',
    'auth.signUp': 'Sign Up',
    'auth.welcomeBack': 'Welkam Bak',
    'auth.createAccount': 'Mek Account',
    'auth.enterEmail': 'Put yu email',
    'auth.enterPassword': 'Put yu password',
    'auth.forgotPassword': 'Yu forget password?',
    'auth.noAccount': 'Yu no get account?',
    'auth.haveAccount': 'Yu don get account?',
    'auth.signInGoogle': 'Sign in wit Google',
    'auth.or': 'OR',
    
    // Onboarding
    'onboarding.welcome': 'Welkam to MiBuks',
    'onboarding.getStarted': 'Mek wi start',
    'onboarding.step1': 'Personal Details',
    'onboarding.step2': 'Business Details',
    'onboarding.step3': 'Complete',
    'onboarding.tellUs': 'Tel wi abou yuself',
    'onboarding.businessDetails': 'Tel wi abou yu business',
    'onboarding.almostDone': 'Wi don almost finish!',
    'onboarding.complete': 'Complete Setup',
    'onboarding.skip': 'Skip fo naw',
    
    // Language
    'language.english': 'English',
    'language.krio': 'Krio',
    'language.french': 'French',
    'language.switch': 'Change Language',
    
    // Business
    'business.defaultname': 'Mi Biznes',
    
    // Messages
    'message.success': 'Success',
    'message.error': 'Error',
    'message.saved': 'E don save',
    'message.deleted': 'E don delete',
    'message.updated': 'E don update',
    'message.created': 'E don create',
    'message.failed': 'Operation fail',
    'message.confirm.delete': 'Yu sure sey yu wan delete dis?',
    'message.confirm.cancel': 'Yu sure sey yu wan cancel?',
    'message.noData': 'No data',
    'message.noResults': 'No results',
  },
  fr: {
    // Navigation
    'nav.dashboard': 'Tableau de bord',
    'nav.invoices': 'Factures',
    'nav.customers': 'Clients',
    'nav.inventory': 'Inventaire',
    'nav.sales': 'Ventes',
    'nav.expenses': 'Dépenses',
    'nav.suppliers': 'Fournisseurs',
    'nav.reports': 'Rapports',
    'nav.credit': 'Crédit et Finance',
    'nav.settings': 'Paramètres',
    'nav.mainmenu': 'Menu Principal',
    
    // Common UI
    'common.search': 'Rechercher transactions, clients...',
    'common.profile': 'Profil',
    'common.signout': 'Déconnexion',
    'common.notifications': 'Notifications',
    'common.administrator': 'Administrateur',
    'common.save': 'Enregistrer',
    'common.cancel': 'Annuler',
    'common.delete': 'Supprimer',
    'common.edit': 'Modifier',
    'common.view': 'Voir',
    'common.add': 'Ajouter',
    'common.create': 'Créer',
    'common.update': 'Mettre à jour',
    'common.close': 'Fermer',
    'common.confirm': 'Confirmer',
    'common.loading': 'Chargement...',
    'common.actions': 'Actions',
    'common.filter': 'Filtrer',
    'common.export': 'Exporter',
    'common.import': 'Importer',
    'common.print': 'Imprimer',
    'common.download': 'Télécharger',
    'common.upload': 'Téléverser',
    'common.submit': 'Soumettre',
    'common.reset': 'Réinitialiser',
    'common.back': 'Retour',
    'common.next': 'Suivant',
    'common.previous': 'Précédent',
    'common.finish': 'Terminer',
    'common.all': 'Tout',
    'common.none': 'Aucun',
    'common.yes': 'Oui',
    'common.no': 'Non',
    'common.status': 'Statut',
    'common.date': 'Date',
    'common.amount': 'Montant',
    'common.total': 'Total',
    'common.subtotal': 'Sous-total',
    'common.tax': 'Taxe',
    'common.discount': 'Remise',
    'common.name': 'Nom',
    'common.email': 'Email',
    'common.phone': 'Téléphone',
    'common.address': 'Adresse',
    'common.description': 'Description',
    'common.notes': 'Notes',
    'common.price': 'Prix',
    'common.quantity': 'Quantité',
    'common.unit': 'Unité',
    'common.category': 'Catégorie',
    'common.type': 'Type',
    'common.details': 'Détails',
    'common.summary': 'Résumé',
    'common.from': 'De',
    'common.to': 'À',
    'common.today': "Aujourd'hui",
    'common.yesterday': 'Hier',
    'common.thisWeek': 'Cette semaine',
    'common.lastWeek': 'Semaine dernière',
    'common.thisMonth': 'Ce mois',
    'common.lastMonth': 'Mois dernier',
    'common.thisYear': 'Cette année',
    'common.select': 'Sélectionner',
    
    // Dashboard
    'dashboard.welcome': 'Bienvenue sur MiBuks',
    'dashboard.goodMorning': 'Bonjour',
    'dashboard.goodAfternoon': 'Bon après-midi',
    'dashboard.goodEvening': 'Bonsoir',
    'dashboard.yourBusiness': 'Votre entreprise',
    'dashboard.user': 'Utilisateur',
    'dashboard.welcomeTo': 'Bienvenue à',
    'dashboard.metrics': 'Indicateurs clés',
    'dashboard.totalRevenue': 'Revenu total',
    'dashboard.fromSales': 'des ventes & factures',
    'dashboard.activeCustomers': 'Clients actifs',
    'dashboard.totalCustomers': 'clients au total',
    'dashboard.inventoryValue': 'Valeur du stock',
    'dashboard.currentStock': 'stock actuel',
    'dashboard.todaySales': "Ventes d'aujourd'hui",
    'dashboard.lowStock': 'Stock faible',
    'dashboard.pendingInvoices': 'Factures en attente',
    'dashboard.invoices': 'factures',
    'dashboard.awaitingPayment': 'en attente de paiement',
    'dashboard.revenueOverview': 'Aperçu des revenus',
    'dashboard.quickActions': 'Actions rapides',
    'dashboard.commonOperations': 'Opérations courantes',
    'dashboard.recordSale': 'Enregistrer une vente',
    'dashboard.createInvoice': 'Créer une facture',
    'dashboard.addCustomer': 'Ajouter un client',
    'dashboard.restockItem': 'Réapprovisionner',
    'dashboard.recentTransactions': 'Transactions récentes',
    'dashboard.viewAll': 'Voir tout',
    
    // Sales
    'sales.title': 'Gestion des ventes',
    'sales.recordSale': 'Enregistrer une vente',
    'sales.saleHistory': 'Historique des ventes',
    'sales.customer': 'Client',
    'sales.items': 'Articles',
    'sales.totalAmount': 'Montant total',
    'sales.paymentMethod': 'Mode de paiement',
    'sales.cash': 'Espèces',
    'sales.card': 'Carte',
    'sales.mobileMoney': 'Mobile Money',
    'sales.credit': 'Crédit',
    'sales.selectCustomer': 'Sélectionner un client',
    'sales.addItem': 'Ajouter un article',
    'sales.item': 'Article',
    'sales.unitPrice': 'Prix unitaire',
    'sales.receiptGenerated': 'Reçu généré',
    'sales.viewReceipt': 'Voir le reçu',
    'sales.printReceipt': 'Imprimer le reçu',
    'sales.date': 'Date',
    'sales.time': 'Heure',
    'sales.itemsSold': 'Articles vendus',
    'sales.noSales': 'Aucune vente enregistrée',
    
    // Inventory
    'inventory.title': 'Gestion des stocks',
    'inventory.description': 'Gérer vos niveaux de stock et inventaire',
    'inventory.loading': 'Chargement de l\'inventaire...',
    'inventory.addItem': 'Ajouter un article',
    'inventory.restock': 'Réapprovisionner',
    'inventory.productName': 'Nom du produit',
    'inventory.sku': 'SKU',
    'inventory.stock': 'Stock',
    'inventory.lowStock': 'Stock faible',
    'inventory.inStock': 'En stock',
    'inventory.outOfStock': 'Rupture de stock',
    'inventory.reorderLevel': 'Niveau de réapprovisionnement',
    'inventory.costPrice': 'Prix de revient',
    'inventory.sellingPrice': 'Prix de vente',
    'inventory.supplier': 'Fournisseur',
    'inventory.barcode': 'Code-barres',
    'inventory.stockValue': 'Valeur du stock',
    'inventory.addQuantity': 'Ajouter une quantité',
    'inventory.currentStock': 'Stock actuel',
    'inventory.newStock': 'Nouveau stock',
    'inventory.noItems': 'Aucun article en stock',
    'inventory.totalItems': 'Total articles',
    'inventory.totalValue': 'Valeur totale',
    'inventory.allItems': 'Tous les articles',
    'inventory.critical': 'Critique',
    'inventory.stockOverview': 'Aperçu du stock',
    'inventory.items': 'articles',
    'inventory.no': 'Aucun',
    'inventory.stockItems': 'articles en stock',
    'inventory.addFirst': 'Ajouter votre premier article',
    'inventory.deleteItem': 'Supprimer l\'article',
    'inventory.deleteConfirm': 'Êtes-vous sûr de vouloir supprimer',
    
    // Invoices
    'invoices.title': 'Factures',
    'invoices.description': 'Créer et gérer les factures',
    'invoices.loading': 'Chargement des factures...',
    'invoices.create': 'Créer une facture',
    'invoices.createInvoice': 'Créer une facture',
    'invoices.confirmDelete': 'Êtes-vous sûr de vouloir supprimer cette facture?',
    'invoices.invoiceNumber': 'Numéro de facture',
    'invoices.invoiceDate': 'Date de facture',
    'invoices.dueDate': "Date d'échéance",
    'invoices.billTo': 'Facturer à',
    'invoices.billFrom': 'Facturer de',
    'invoices.paid': 'Payée',
    'invoices.unpaid': 'Non payée',
    'invoices.overdue': 'En retard',
    'invoices.partial': 'Partiellement payée',
    'invoices.cancelled': 'Annulée',
    'invoices.draft': 'Brouillon',
    'invoices.issued': 'Émise',
    'invoices.amountDue': 'Montant dû',
    'invoices.amountPaid': 'Montant payé',
    'invoices.balance': 'Solde',
    'invoices.sendInvoice': 'Envoyer la facture',
    'invoices.markAsPaid': 'Marquer comme payée',
    'invoices.applyCredit': 'Appliquer le crédit',
    'invoices.noInvoices': 'Aucune facture',
    
    // Customers
    'customers.title': 'Clients',
    'customers.addCustomer': 'Ajouter un client',
    'customers.firstName': 'Prénom',
    'customers.lastName': 'Nom de famille',
    'customers.companyName': 'Nom de la société',
    'customers.contactPerson': 'Personne de contact',
    'customers.totalSpent': 'Total dépensé',
    'customers.lastPurchase': 'Dernier achat',
    'customers.creditBalance': 'Solde de crédit',
    'customers.birthdate': 'Date de naissance',
    'customers.notes': 'Notes du client',
    'customers.purchaseHistory': "Historique d'achats",
    'customers.noCustomers': 'Aucun client',
    
    // Suppliers
    'suppliers.title': 'Fournisseurs',
    'suppliers.addSupplier': 'Ajouter un fournisseur',
    'suppliers.supplierName': 'Nom du fournisseur',
    'suppliers.totalOrders': 'Commandes totales',
    'suppliers.lastOrder': 'Dernière commande',
    'suppliers.outstanding': 'En attente',
    'suppliers.products': 'Produits fournis',
    'suppliers.noSuppliers': 'Aucun fournisseur',
    
    // Expenses
    'expenses.title': 'Dépenses',
    'expenses.addExpense': 'Ajouter une dépense',
    'expenses.expenseCategory': 'Catégorie de dépense',
    'expenses.rent': 'Loyer',
    'expenses.utilities': 'Services publics',
    'expenses.salaries': 'Salaires',
    'expenses.supplies': 'Fournitures',
    'expenses.marketing': 'Marketing',
    'expenses.transport': 'Transport',
    'expenses.maintenance': 'Entretien',
    'expenses.other': 'Autre',
    'expenses.receipt': 'Reçu',
    'expenses.uploadReceipt': 'Téléverser le reçu',
    'expenses.totalExpenses': 'Dépenses totales',
    'expenses.noExpenses': 'Aucune dépense enregistrée',
    
    // Reports
    'reports.title': 'Rapports et analyses',
    'reports.salesReport': 'Rapport des ventes',
    'reports.inventoryReport': 'Rapport des stocks',
    'reports.profitLoss': 'Profits et pertes',
    'reports.cashFlow': 'Flux de trésorerie',
    'reports.taxReport': 'Rapport fiscal',
    'reports.generateReport': 'Générer un rapport',
    'reports.period': 'Période',
    'reports.exportPDF': 'Exporter en PDF',
    'reports.exportExcel': 'Exporter en Excel',
    'reports.revenue': 'Revenu',
    'reports.expenses': 'Dépenses',
    'reports.profit': 'Profit',
    'reports.loss': 'Perte',
    'reports.netIncome': 'Revenu net',
    
    // Credit & Finance
    'credit.title': 'Crédit et Finance',
    'credit.creditScore': 'Score de crédit',
    'credit.loanApplications': 'Demandes de prêt',
    'credit.applyForLoan': 'Demander un prêt',
    'credit.loanAmount': 'Montant du prêt',
    'credit.loanPurpose': 'Objectif du prêt',
    'credit.repaymentPeriod': 'Période de remboursement',
    'credit.monthlyPayment': 'Paiement mensuel',
    'credit.interestRate': "Taux d'intérêt",
    'credit.approved': 'Approuvé',
    'credit.pending': 'En attente',
    'credit.rejected': 'Rejeté',
    'credit.creditHistory': 'Historique de crédit',
    
    // Settings
    'settings.title': 'Paramètres',
    'settings.profile': 'Profil',
    'settings.business': 'Entreprise',
    'settings.team': 'Équipe',
    'settings.security': 'Sécurité',
    'settings.notifications': 'Notifications',
    'settings.preferences': 'Préférences',
    'settings.data': 'Données',
    'settings.profileInfo': 'Informations du profil',
    'settings.businessInfo': "Informations de l'entreprise",
    'settings.firstName': 'Prénom',
    'settings.lastName': 'Nom de famille',
    'settings.phoneNumber': 'Numéro de téléphone',
    'settings.emailAddress': 'Adresse email',
    'settings.businessName': "Nom de l'entreprise",
    'settings.businessType': "Type d'entreprise",
    'settings.businessAddress': "Adresse de l'entreprise",
    'settings.taxRate': 'Taux de taxe',
    'settings.currency': 'Devise',
    'settings.changePassword': 'Changer le mot de passe',
    'settings.currentPassword': 'Mot de passe actuel',
    'settings.newPassword': 'Nouveau mot de passe',
    'settings.confirmPassword': 'Confirmer le mot de passe',
    'settings.twoFactor': 'Authentification à deux facteurs',
    'settings.emailNotifications': 'Notifications par email',
    'settings.smsNotifications': 'Notifications par SMS',
    'settings.lowStockAlerts': 'Alertes de stock faible',
    'settings.newOrderAlerts': 'Alertes de nouvelles commandes',
    'settings.paymentAlerts': 'Alertes de paiement',
    'settings.theme': 'Thème',
    'settings.light': 'Clair',
    'settings.dark': 'Sombre',
    'settings.system': 'Système',
    'settings.language': 'Langue',
    'settings.dateFormat': 'Format de date',
    'settings.timeFormat': "Format d'heure",
    'settings.autoBackup': 'Sauvegarde automatique',
    'settings.compactView': 'Vue compacte',
    'settings.exportData': 'Exporter les données',
    'settings.importData': 'Importer les données',
    'settings.deleteAccount': 'Supprimer le compte',
    'settings.saveChanges': 'Enregistrer les modifications',
    'settings.teamManagement': "Gestion de l'équipe",
    'settings.inviteMember': 'Inviter un membre',
    'settings.memberRole': 'Rôle du membre',
    'settings.owner': 'Propriétaire',
    'settings.manager': 'Gestionnaire',
    'settings.staff': 'Personnel',
    'settings.accountSecurity': 'Sécurité du compte',
    'settings.loginHistory': 'Historique de connexion',
    'settings.weeklyReports': 'Rapports hebdomadaires',
    'settings.monthlyReports': 'Rapports mensuels',
    
    // Auth
    'auth.signIn': 'Se connecter',
    'auth.signUp': "S'inscrire",
    'auth.welcomeBack': 'Bienvenue',
    'auth.createAccount': 'Créer un compte',
    'auth.enterEmail': 'Entrez votre email',
    'auth.enterPassword': 'Entrez votre mot de passe',
    'auth.forgotPassword': 'Mot de passe oublié?',
    'auth.noAccount': "Vous n'avez pas de compte?",
    'auth.haveAccount': 'Vous avez déjà un compte?',
    'auth.signInGoogle': 'Se connecter avec Google',
    'auth.or': 'OU',
    
    // Onboarding
    'onboarding.welcome': 'Bienvenue sur MiBuks',
    'onboarding.getStarted': 'Commençons',
    'onboarding.step1': 'Détails personnels',
    'onboarding.step2': "Détails de l'entreprise",
    'onboarding.step3': 'Terminer',
    'onboarding.tellUs': 'Parlez-nous de vous',
    'onboarding.businessDetails': 'Parlez-nous de votre entreprise',
    'onboarding.almostDone': 'Presque terminé!',
    'onboarding.complete': 'Terminer la configuration',
    'onboarding.skip': 'Passer pour le moment',
    
    // Language
    'language.english': 'Anglais',
    'language.krio': 'Krio',
    'language.french': 'Français',
    'language.switch': 'Changer de langue',
    
    // Business
    'business.defaultname': 'Mon entreprise',
    
    // Messages
    'message.success': 'Succès',
    'message.error': 'Erreur',
    'message.saved': 'Enregistré avec succès',
    'message.deleted': 'Supprimé avec succès',
    'message.updated': 'Mis à jour avec succès',
    'message.created': 'Créé avec succès',
    'message.failed': 'Opération échouée',
    'message.confirm.delete': 'Êtes-vous sûr de vouloir supprimer ceci?',
    'message.confirm.cancel': 'Êtes-vous sûr de vouloir annuler?',
    'message.noData': 'Aucune donnée disponible',
    'message.noResults': 'Aucun résultat trouvé',
  }
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en')

  useEffect(() => {
    const savedLanguage = localStorage.getItem('mibuks-language') as Language
    if (savedLanguage && (savedLanguage === 'en' || savedLanguage === 'krio' || savedLanguage === 'fr')) {
      setLanguage(savedLanguage)
    }
  }, [])

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    localStorage.setItem('mibuks-language', lang)
  }

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}