// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lgstierfmiezdeqhwyap.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxnc3RpZXJmbWllemRlcWh3eWFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1MTQzMzgsImV4cCI6MjA3MDA5MDMzOH0.4yIqlsfe9N7glx8B2csBv1u9GdwOz1Ob4rLZQQa5ihM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});